### ISSUE TITLE
Documentation `~/.prismrc` file

### ISSUE THREAD

**Issue by martinheidegger** [jcubic/prism-cli#9]
I noticed while reading through the code that prism-cli supports a `~/.prismrc` file but it is not documented how to use it, maybe its a good idea to add that?

https://github.com/jcubic/prism-cli/blob/e4b02149128b8fe8e4b19869bea2e37bc7045fba/prism.js#L10-L11

**Comment by jcubic** [comment]
Thanks for the issue, it seems that I've missed issues for this project. Will work on it in few days, I will add code for node module and some screenshots.

**Comment by jcubic** [comment]
Docs added to README.
